sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS

branches:
  only:
    - source # build master branch only

install:
  - npm install 

script:
  - hexo clean
  - hexo g -d

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: source
    local-dir: public
    target-branch:
      master
  - provider: pages
    skip-cleanup: true
    github-token: $CO_TOKEN
    keep-history: true
    on:
      branch: source
    local-dir: public
    target-branch: master
