sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS

branches:
  only:
    - source # build master branch only

install:
  - npm install 

script:
  - hexo clean
  - hexo g && gulp
after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m 'travis'
  - git push --force --quiet "https://MCsqyjFdnu:$CO_TOKEN@e.coding.net/muyed/muyed.git" master:master

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: source
    local-dir: public
    target-branch:
      master
