sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS

branches:
  only:
    - source # build master branch only

install:
  - npm install 

script:
  - hexo clean
  - hexo g -d # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: source
  target-branch:
    master
